[versions]
agpVersion = "9.2.1"
appcompat = "1.7.1"
coreKtx = "1.18.0"
kotlinVersion = "2.3.21"
exifinterface = "1.4.2"
lifecycleService = "2.10.0"
material = "1.14.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agpVersion" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }

